/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#006e2f",
        "primary-container": "#00b050",
        "outline-variant": "#bccbb9",
        "on-surface": "#111c2c",
        "on-surface-variant": "#3d4a3d",
        "background": "#f9f9ff",
        "surface": "#f9f9ff",
        "surface-container-low": "#f0f3ff",
        "surface-container-highest": "#d8e3fa",
        "outline": "#6d7b6c",
        "secondary-container": "#b8ecc3",
        "on-secondary-container": "#3d6c4c",
        "error": "#ba1a1a",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed": "#baefc6",
        "tertiary-container": "#929b97",
        "on-secondary-fixed": "#00210e",
        "surface-dim": "#cfdaf1",
        "surface-tint": "#006e2f",
        "surface-variant": "#d8e3fa",
        "on-tertiary": "#ffffff",
        "error-container": "#ffdad6",
        "on-primary-fixed-variant": "#005322",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#bfc9c4",
        "on-tertiary-container": "#2a3330",
        "tertiary-fixed": "#dce5e0",
        "on-secondary": "#ffffff",
        "inverse-surface": "#263142",
        "surface-bright": "#f9f9ff",
        "on-primary-container": "#003a15",
        "inverse-primary": "#52e079",
        "inverse-on-surface": "#ebf1ff",
        "primary-fixed": "#71fe93",
        "on-primary-fixed": "#002109",
        "on-background": "#111c2c",
        "tertiary": "#57605d",
        "on-tertiary-fixed": "#151d1b",
        "surface-container": "#e7eeff",
        "secondary-fixed-dim": "#9fd3ab",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#52e079",
        "surface-container-high": "#dee8ff",
        "secondary": "#396848",
        "on-secondary-fixed-variant": "#205032",
        "on-tertiary-fixed-variant": "#404945",
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "unit": "4px",
        "margin-mobile": "16px",
        "xs": "4px",
        "xl": "48px",
        "sm": "8px",
        "lg": "24px",
        "gutter": "24px",
        "container-max": "1280px",
        "md": "16px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Be Vietnam Pro"],
        "headline-lg": ["Be Vietnam Pro"],
        "body-lg": ["Be Vietnam Pro"],
        "headline-md": ["Be Vietnam Pro"],
        "display-lg": ["Be Vietnam Pro"],
        "label-bold": ["Work Sans"],
        "body-md": ["Be Vietnam Pro"],
        "label-sm": ["Work Sans"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "1.3", "fontWeight": "700" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "1.4", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "label-bold": ["14px", { "lineHeight": "1.2", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-sm": ["12px", { "lineHeight": "1.2", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
