-- Correction for the legacy batch code generated by 20260803231000: it is
-- based on StoreInventory.id, so assignment must resolve by store + variant.
INSERT INTO "order_item_batch_allocations" (
  "id", "order_item_id", "batch_id", "quantity", "status", "created_at", "updated_at"
)
SELECT
  'legacy-open-order-' || oi."id",
  oi."id",
  batch."id",
  oi."quantity",
  'RESERVED'::"BatchAllocationStatus",
  o."created_at",
  CURRENT_TIMESTAMP
FROM "order_items" oi
JOIN "orders" o ON o."id" = oi."order_id"
JOIN LATERAL (
  SELECT ib."id"
  FROM "inventory_batches" ib
  WHERE ib."store_id" = o."store_id" AND ib."variant_id" = oi."variant_id"
  ORDER BY
    CASE WHEN ib."batch_code" LIKE 'LEGACY-%' THEN 0 ELSE 1 END,
    ib."expiry_date" ASC,
    ib."received_date" ASC
  LIMIT 1
) batch ON TRUE
WHERE o."status" IN (
  'PENDING_PAYMENT', 'PLACED', 'STORE_CONFIRMED', 'PICKING', 'PACKED',
  'READY_FOR_DELIVERY', 'OUT_FOR_DELIVERY', 'DELIVERY_FAILED'
)
ON CONFLICT ("id") DO NOTHING;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1
    FROM "inventory_batches" ib
    JOIN (
      SELECT "batch_id", SUM("quantity") AS reserved_quantity
      FROM "order_item_batch_allocations"
      WHERE "status" = 'RESERVED'::"BatchAllocationStatus"
      GROUP BY "batch_id"
    ) pending ON pending."batch_id" = ib."id"
    WHERE pending.reserved_quantity > ib."quantity_on_hand"
  ) THEN
    RAISE EXCEPTION 'Cannot reconcile batch reservations: open orders exceed batch stock';
  END IF;
END $$;

-- Allocation rows are authoritative. Rebuild both reservation projections to
-- remove legacy drift and make subsequent commit/release operations exact.
UPDATE "inventory_batches" SET "reserved_quantity" = 0, "updated_at" = CURRENT_TIMESTAMP;

WITH pending AS (
  SELECT "batch_id", SUM("quantity") AS quantity
  FROM "order_item_batch_allocations"
  WHERE "status" = 'RESERVED'::"BatchAllocationStatus"
  GROUP BY "batch_id"
)
UPDATE "inventory_batches" ib
SET "reserved_quantity" = pending.quantity,
    "updated_at" = CURRENT_TIMESTAMP
FROM pending
WHERE ib."id" = pending."batch_id";

UPDATE "store_inventories" SET "reserved_quantity" = 0, "updated_at" = CURRENT_TIMESTAMP;

WITH pending AS (
  SELECT ib."store_id", ib."variant_id", SUM(a."quantity") AS quantity
  FROM "order_item_batch_allocations" a
  JOIN "inventory_batches" ib ON ib."id" = a."batch_id"
  WHERE a."status" = 'RESERVED'::"BatchAllocationStatus"
  GROUP BY ib."store_id", ib."variant_id"
)
UPDATE "store_inventories" si
SET "reserved_quantity" = pending.quantity,
    "updated_at" = CURRENT_TIMESTAMP
FROM pending
WHERE si."store_id" = pending."store_id" AND si."variant_id" = pending."variant_id";
